from pipelines.ec2_idle import EC2IdlePipeline
from pipelines.ebs_unused import EBSUnusedPipeline
from pipelines.ec2_unused import EC2UnusedPipeline
from pipelines.eip_unused import EIPUnusedPipeline
from pipelines.logs_never_expire import LogsNeverExpirePipeline
from pipelines.logs_high_ingestion import LogsHighIngestionPipeline